--2021年11月22

INSERT INTO SYS_WEB_MODULE(MODULE_TYPE,MODULE_CODE,MODULE_NAME,MODULE_URL,MODULE_FILE,MODIFY_FILE,PARENT_CODE,IS_GROUP,PICTURE_NAME,IS_AVAILABLE) VALUES ('01','1000200','活动报名','','','','1000000',0,'el-icon-document',1)
INSERT INTO SYS_FUNCTION (FUNCTION_ID ,MODULE_CODE ,FUNCTION_CODE ,FUNCTION_NAME,IS_CUSTOM) VALUES ('100020020','1000200',20,'Module',0)
INSERT INTO SYS_FUNCTION (FUNCTION_ID ,MODULE_CODE ,FUNCTION_CODE ,FUNCTION_NAME,IS_CUSTOM) VALUES ('100020030','1000200',30,'查询',0)
INSERT INTO SYS_FUNCTION (FUNCTION_ID ,MODULE_CODE ,FUNCTION_CODE ,FUNCTION_NAME,IS_CUSTOM) VALUES ('100020032','1000200',32,'编辑',0)
INSERT INTO SYS_FUNCTION (FUNCTION_ID ,MODULE_CODE ,FUNCTION_CODE ,FUNCTION_NAME,IS_CUSTOM) VALUES ('100020033','1000200',33,'删除',0)
GO
PRINT 'CREATE TABLE APP_ACTIVITY_ENROLL'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_ACTIVITY_ENROLL') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_ACTIVITY_ENROLL]
GO

CREATE TABLE APP_ACTIVITY_ENROLL
(
	ENROLL_ID	Decimal(9)	IDENTITY (1,1)	NOT NULL,
	ACTIVITY_NO	Nvarchar(20)		NOT NULL,
	USER_NAME	Nvarchar (20)		NOT NULL,
	COMPANY	Nvarchar (100)		NOT NULL,
	POSITION	Nvarchar (20)		NOT NULL,
	MOBILE	Nvarchar (11)		NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,

	constraint APP_ACTIVITY_ENROLL_PK PRIMARY KEY CLUSTERED (ENROLL_ID)
)
GO


PRINT 'CREATE TABLE APP_SMS'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_SMS]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_SMS]
GO

CREATE TABLE APP_SMS
(
	SMS_ID	Decimal(9)	IDENTITY (1,1)	NOT NULL,
	SMS_NO	Nvarchar (20)		NOT NULL,
	SMS_TYPE	Nvarchar (10)		NOT NULL,
	USER_ID	Decimal(9)		NULL,
	MOBILE	Nvarchar (20)		NOT NULL,
	NUMBER	Nvarchar (6)		NULL,
	MESSAGE	Nvarchar(200)		NULL,
	IS_READ	Int	Default(0)	NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	Datetime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,


	constraint APP_SMS_PK PRIMARY KEY CLUSTERED (SMS_ID)
)
GO
CREATE UNIQUE INDEX APP_SMS_IDX01 ON APP_SMS (SMS_NO)
GO

alter table APP_SCHOOL add	
FILE_ID	Decimal(9)		NULL,
NICK_NAME	Nvarchar(20)		NULL
GO

alter table APP_SETUP add	
SERVICE_CLAUSE	Text		NULL
GO

alter table APP_HONOR add	
HONOR_EN	Text		NULL
GO

alter table APP_FACILITIES add	
TITLE_EN	Nvarchar (100)		 NULL	
GO

--时间 2021.11.25




PRINT 'CREATE TABLE APP_JUDGES'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_JUDGES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_JUDGES]
GO

CREATE TABLE APP_JUDGES
(
	JUDGES_ID	Decimal(9)	IDENTITY (1,1)	NOT NULL,
	JUDGES_NO	Nvarchar(20)		NOT NULL,
	NICK_NAME	Nvarchar(20)		NOT NULL,
	MOBILE	Nvarchar(20)		NOT NULL,
	USER_PWD	Nvarchar(120)		NOT NULL,
	IMAGE_ID	Decimal(9)		NULL,
	PROVINCE_NO	Nvarchar (6)		NULL,
	CITY_NO	Nvarchar (6)		NULL,
	DISYRICT_NO	Nvarchar (6)		NULL,
	ADDRESS	Nvarchar (200)		NULL,
	COMPANY	Nvarchar (200)		NULL,
	POSITION	Nvarchar(20)		NULL,
	LINK_TEL	Nvarchar(20)		NULL,
	LINK_MAN	Nvarchar(20)		NULL,
	EMAIL	Nvarchar(20)		NULL,
	WECHAT	Nvarchar(20)		NULL,
	CLIENT_ID	Nvarchar(50)		NULL,
	IS_ENABLED	Int	Default(0)	NOT NULL,
	IS_MAIN	Int	Default(0)	NOT NULL,
	IS_SPECIAL	Int	Default(0)	NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,


	constraint APP_JUDGES_PK PRIMARY KEY CLUSTERED (JUDGES_ID)
)
GO
CREATE UNIQUE INDEX APP_JUDGES_IDX01 ON APP_JUDGES (JUDGES_NO)
GO


PRINT 'CREATE TABLE APP_JUDGES_HONOR'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_JUDGES_HONOR]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_JUDGES_HONOR]
GO

CREATE TABLE APP_JUDGES_HONOR
(
	HONOR_ID	Decimal(9)	IDENTITY (1,1)		NOT NULL,
	JUDGES_NO	Nvarchar(20)		NOT NULL,
	HONOR_TYPE	Nvarchar(20)		NOT NULL,
	HONOR_YEAR	Nvarchar (20)		NOT NULL,
	HONOR_DESC	Nvarchar (200)		NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,



	constraint APP_JUDGES_HONOR_PK PRIMARY KEY CLUSTERED (HONOR_ID)
)
GO

PRINT 'CREATE TABLE APP_QUESTIONNAIRE'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_QUESTIONNAIRE]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_QUESTIONNAIRE]
GO

CREATE TABLE APP_QUESTIONNAIRE
(
	QUESTIONNAIRE_ID	Decimal(9)	IDENTITY (1,1)		NOT NULL,
	QUESTIONNAIRE_NO	Nvarchar(20)		NOT NULL,
	QUESTIONNAIRE_TITLE	Nvarchar (50)		NULL,
	QUESTIONNAIRE_CONTENT	Text		NULL,
	QUESTIONNAIRE_START	DateTime		NULL,
	QUESTIONNAIRE_END	DateTime		NULL,
	IS_ENABLED	Int	Default(0)	NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,


	constraint APP_QUESTIONNAIRE_PK PRIMARY KEY CLUSTERED (QUESTIONNAIRE_ID)
)
GO
CREATE UNIQUE INDEX APP_QUESTIONNAIRE_IDX01 ON APP_QUESTIONNAIRE (QUESTIONNAIRE_NO)
GO


PRINT 'CREATE TABLE APP_QUESTIONNAIRE_ITEM'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_QUESTIONNAIRE_ITEM]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_QUESTIONNAIRE_ITEM]
GO

CREATE TABLE APP_QUESTIONNAIRE_ITEM
(
	ITEM_ID	Decimal(9)	IDENTITY (1,1)		NOT NULL,
	QUESTIONNAIRE_NO	Nvarchar(20)		NOT NULL,
	TITLE	Nvarchar (50)		NOT NULL,
	RESULT_MAX	Int	Default(5)	NOT NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,

	constraint APP_QUESTIONNAIRE_ITEM_PK PRIMARY KEY CLUSTERED (ITEM_ID)
)
GO


PRINT 'CREATE TABLE APP_QUESTIONNAIRE_JUDGES'
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[APP_QUESTIONNAIRE_JUDGES]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[APP_QUESTIONNAIRE_JUDGES]
GO

CREATE TABLE APP_QUESTIONNAIRE_JUDGES
(
	RESULT_ID	Decimal(9)	IDENTITY (1,1)		NOT NULL,
	QUESTIONNAIRE_NO	Nvarchar(20)		NOT NULL,
	JUDGES_NO	Nvarchar(20)		NOT NULL,
	ITEM_ID	Decimal(9)		NOT NULL,
	TITLE	Nvarchar (50)		NOT NULL,
	SCHOOL_NAME	Nvarchar (50)		NULL,
	REASON	Nvarchar (200)		NULL,
	REMARK	Nvarchar(200)		NULL,
	CREATE_TIME	DateTime		NOT NULL,
	UPDATE_TIME	DateTime		NOT NULL,

	constraint APP_QUESTIONNAIRE_JUDGES_ITEM_PK PRIMARY KEY CLUSTERED (RESULT_ID)
)
GO