TRUNCATE TABLE BASE_CLASS
INSERT INTO BASE_CLASS (CLASS_NO ,CLASS_NAME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES ('01','招生对象',1,GETDATE(),1,GETDATE())
INSERT INTO BASE_CLASS (CLASS_NO ,CLASS_NAME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES ('02','体育设施',1,GETDATE(),1,GETDATE())
INSERT INTO BASE_CLASS (CLASS_NO ,CLASS_NAME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES ('03','艺术设施',1,GETDATE(),1,GETDATE())
INSERT INTO BASE_CLASS (CLASS_NO ,CLASS_NAME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES ('04','学术设施',1,GETDATE(),1,GETDATE())
INSERT INTO BASE_CLASS (CLASS_NO ,CLASS_NAME,CREATE_BY,CREATE_TIME,UPDATE_BY,UPDATE_TIME) VALUES ('05','课程体系',1,GETDATE(),1,GETDATE())

